apiVersion: ottoplus.io/v1alpha1
kind: Cluster
metadata:
  name: demo-pg
  namespace: ottoplus
spec:
  blocks:
    composition:
      - kind: storage.local-pv
        name: storage
        parameters:
          size: "5Gi"

      - kind: datastore.postgresql
        name: db
        parameters:
          version: "16"
          replicas: "3"
        inputs:
          storage: storage/pvc-spec

      - kind: gateway.pgbouncer
        name: pooler
        inputs:
          upstream-dsn: db/dsn
