name: Unit Tests

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/**'
      - 'Makefile'
      - 'go.mod'
      - 'go.sum'
      - 'deploy/examples/**'
      - 'src/**'
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/**'
      - 'Makefile'
      - 'go.mod'
      - 'go.sum'
      - 'deploy/examples/**'
      - 'src/**'

permissions:
  contents: read

concurrency:
  group: unit-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit:
    name: Unit Check
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Unit tests
        run: make test
